Repository coreweave/tensorizer, pull requests merged in 2024-02, with the labels that each got.

#75 fix(serialization): Don't drop parameters with non-persistent buffers
  CHANGELOG.md
  tensorizer/_version.py
  tensorizer/serialization.py
  tests/test_serialization.py
Labels: bug

#76 feat(examples): Support S3 for all `StableDiffusionPipeline` components
  CHANGELOG.md
  examples/hf_serialization.py
  tensorizer/_version.py
  tensorizer/serialization.py
  tests/test_serialization.py
Labels: enhancement

#73 feat(examples): Update `hf_serialization.py` to be used as Kubernetes Job container
  examples/hf_serialization.py
Labels: enhancement

#79 feat(serialization): Default to `plaid_mode=True` for CUDA tensors
  CHANGELOG.md
  README.md
  examples/deserialize.py
  examples/encryption.py
  tensorizer/_version.py
  tensorizer/serialization.py
  tests/test_serialization.py
Labels: enhancement

#82 fix(serialization): Support serializing tensors over `write` size limits
  CHANGELOG.md
  tensorizer/serialization.py
  tests/test_serialization.py
Labels: bug

#85 perf(serialization): Use Linux `fallocate` instead of `posix_fallocate`
  tensorizer/_syscalls.py
  tensorizer/serialization.py
  tests/test_syscalls.py
Labels: enhancement

#86 tests: Add test for behaviour of out-of-order `pwrite` calls
  tests/test_syscalls.py
Labels: enhancement

#88 perf(serialization): Use optimal linear partitioning to divide segments
  tensorizer/_linear_partition.py
  tensorizer/serialization.py
Labels: enhancement

#91 fix(examples): Move non-persistent buffers to a valid device
  examples/deserialize.py
Labels: bug

#95 docs: Update `plaid_mode` stats in the README
  README.md
Labels: documentation

#96 fix(examples): Generate non-persistent buffers on the intended device
  README.md
  examples/deserialize.py
Labels: documentation

#98 perf(serialization) Reuse a pinned buffer when copying from gpu
  tensorizer/serialization.py
Labels: enhancement

#100 fix(serialization): Limit `read_numpy_arrays` to CPU deserialization
  tensorizer/serialization.py
Labels: bug

#97 fix(stream_io): Use region & signature version on S3 writes; use kwargs
  tensorizer/stream_io.py
Labels: bug

#99 fix: Avoid regressions, add tests, better reference handling, misc. logic errors
  README.md
  tensorizer/_linear_partition.py
  tensorizer/_wide_pipes.py
  tensorizer/serialization.py
  tensorizer/stream_io.py
  tests/test_serialization.py
  tests/test_stream_io.py
Labels: bug, enhancement

#87 Major refactor of deserialization to support concurrent readers for performance
  README.md
  examples/benchmark_buffer_size/benchmark.py
  examples/deserialize-simple.py
  examples/deserialize.py
  pyproject.toml
  requirements.txt
  tensorizer/_linear_partition.py
  tensorizer/_wide_pipes.py
  tensorizer/serialization.py
  tensorizer/stream_io.py
  tests/test_serialization.py
  tests/test_stream_io.py
Labels: enhancement
